### ISSUE TITLE
Retriever module only retrieves items from one inventory when using tag/nbt filter

### ISSUE THREAD

**Issue by Corfiot** [Ellpeck/PrettyPipes#105]
Connect three chests. Add a retrieval module to chest A. Set type to e.g. an ingot.
Add ingots to chest B and C.
Works.

Now add a tag or nbt filter to chest A pipe.
Pipe only retrieves items from one chest.

Using MC 1.16.5 on java 17.0.1 64 bit

Thank you for this mod.

**Comment by Ellpeck** [comment]
As you can see, I cannot reproduce this issue with the setup you provided. Please try to reproduce it without any other mods installed.

https://user-images.githubusercontent.com/5741138/146682710-f6010b5e-4b95-4d81-b749-bad61cac11e6.mp4

**Comment by Corfiot** [comment]
I don't have the time to do full mod elimination cause of the sheer amount of mods, it's a modpack (Enigmatica 6 E6 - 1.16.5),

However:
I've retested with your setup and it works but I managed to break it by adding and removing the second part to the receiving chest (making it a double chest).

once it's stuck with a double receiving chest, changing the filter won't unstuck it, seems like it loses mapping to the second chest.

I have a video how do you upload those here

**Comment by Ellpeck** [comment]
Double chests behave weirdly in 1.16, sadly. You should be able to fix your setup by breaking and replacing the chest that used to be a double chest, but other than that, there's nothing I can do since the 1.16 version isn't supported anymore.

This issue should be gone in the 1.18 version, though, since the way chests are handled by Minecraft/Forge is a lot more consistent now.

**Comment by Corfiot** [comment]
Thank you for your reply.
