### ISSUE TITLE
Buggy interaction between Prettypipes and StorageDrawers

### ISSUE THREAD

**Issue by TRUELIKEtheRIVER** [Ellpeck/PrettyPipes#107]
When a crafting terminal is connected via a pipe system to two or more Drawer Controllers from Storage Drawers in the same Storage Drawers network,  it counts each controller as a seperate inventory,

https://cdn.discordapp.com/attachments/661400208399269898/922050918923522088/unknown.png (with two drawer controllers connected, 

https://cdn.discordapp.com/attachments/661400208399269898/922051152705626112/unknown.png actual diamond storage

https://cdn.discordapp.com/attachments/661400208399269898/922051294997409792/unknown.png What it looks like with three drawer controllers connected to the network.

**Comment by IdrisQe** [comment]
Yeah, my system is having issues too now, though I have no controllers connected. The terminal is, for some reason, interpreting *some* of my drawers, seemingly at random, as having 2x the amount they actually have. All of my affected drawers are connected to the pipes via 1 side, and all hold 2 types of item (but ALL of my drawers are the 2x16stack ones so that's not an issue) there's seemingly nothing different about these drawers nore the pipes connecting them, but as long as there is even 1 of an item in the drawer, the Item Terminal thinks there's twice as many... but again, only SOME drawers... no idea why.

**Comment by Ellpeck** [comment]
This is a really old Storage Drawers issue.
