### ISSUE TITLE
Duplication of stored items

### ISSUE THREAD

**Issue by mclap40** [Ellpeck/PrettyPipes#152]
Good afternoon, the following report is to report a problem that I have detected in the mod. When entering items and seeing the amount that appear in the chests, for some reason it duplicates them. That is to say, if I put two iron ingots, when I look at the inventory it tells me that I have 4, and when I remove 2 it takes out all of it. The problem is that when entering the items, it always marks double the amount that is actually stored in the inventory. It would be possible to correct this. Thank you very much for your work.

**Comment by Ellpeck** [comment]
Hi! What version of Minecraft and Pretty Pipes are you using?

If you're still on the 1.16 version, this issue might be occuring because you connected a vanilla Minecraft double chest to the network using two pipes. For other inventories, this generally isn't a problem, but 1.16 vanilla chests unfortunately don't cooperate well with Forge's `IItemHandler` system and, as such, cause this issue.

**Comment by mclap40** [comment]
Hello again. The mod version I'm using is PrettyPipes-1.12.6.jar and the Minecraft version is 1.18.2 with Forge and Mods.

**Comment by Ellpeck** [comment]
Hmm, are there any storage containers (not just vanilla chests) that you have connected to the network twice? If so, can you try removing one of the connections and seeing if the issue gets resolved? 

Please also let me know what container was causing the issue in that case, too!

**Comment by Mattabase** [comment]
Still happening in FTB stone block today with their andesite and stone chest types a

**Comment by Ellpeck** [comment]
> Still happening in FTB stone block today with their andesite and stone chest types a

Does this issue happen with vanilla chests too?

If not: since Forge has changed how it wraps vanilla chests' item handling since 1.16, the andesite and stone chests might also be using the outdated way that was previously used, which caused this issue. There's nothing that can quickly and easily be done on Pretty Pipes' end to mitigate this.
