### ISSUE TITLE
Bug or intended? Crafting Terminal Not finding items that have a Extraction filter?

### ISSUE THREAD

**Issue by chyper111** [Ellpeck/PrettyPipes#31]
I want to pro sort with your awesome pipes please helps?

**Comment by Ellpeck** [comment]
Yes, that is intended behavior. Just add a second pipe to your container if you want it to be sorted, or use a retrieval module instead.

**Comment by chyper111** [comment]
Well I wanted a simple sorting system that could sort with the extraction filter and that would pull all from one pipe because its connected. I really don't need it to just pull any one item into another or my inventory if you get time it would be cool if you allowed the terminals to pull from the chest regardless of filter. If not thanks for the cool mod anyway btw this mod is one of the best simple pipe mods I've ever seen in all the years I've played Minecraft well done.

**Comment by Ellpeck** [comment]
How would extraction modules help you with sorting?

The item you want in your storage destination chests is Filters, they only let items through that you specify. Your input chest then has to have an Extraction module on it, and things like furnaces (that smelt all ores that are in your storage chests) can use Retrieval modules.

Items being extracted by the terminal from chests that have Extraction modules in them makes no sense, because chests with extraction modules should not be considered a part of the storage system. They're merely an input into the storage system.
