### ISSUE TITLE
crash with auto crafting a looping craft

### ISSUE THREAD

**Issue by ziwu07** [Ellpeck/PrettyPipes#68]
I set up an auto craft with both a 9 iron ingot to 1 iron block, and a 1 iron block to 9 iron ingot, and when I requested an iron block the game crashed

**Comment by Ellpeck** [comment]
Please try if it's fixed with this version, but please make sure to also test regular (non-recursive) and more complex crafting operations that involve multiple crafts etc, since this might have broken those lol
https://ci.ellpeck.de/job/PrettyPipes/job/main/19/artifact/build/libs/PrettyPipes-1.9.0.19.jar
