### ISSUE TITLE
Pretty Pipes don't extract if a Storage Drawer with a void upgrade is the target

### ISSUE THREAD

**Issue by NillerMedDild** [Ellpeck/PrettyPipes#94]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3067

> If you use Pretty Pipes to extract items from inventories, items are not extracted if they would go into a Storage Drawer that has a void upgrade on it, regardless of whether it is actually full. Other items are extracted normally, and the extraction of the problematic items resumes immediately if you remove the void upgrade from the target drawer.
The problem is retained if you have a secord target inventory with a lower priority in your system. If the target with the highest priority is a drawer with a void upgrade, the items will remain in their source inventory.

### Versions
- PrettyPipes-1.9.4
- Forge-1.16.5-36.2.2

**Comment by Ellpeck** [comment]
Last time I investigated issues like this, Storage Drawers' implementation of Forge's item handles wasn't in line with the way they were supposed to work according to Forge's documentation, causing a lot of item transport mods to have confusing or incorrect behavior.

Since I don't know if this is still the case, reporting this issue to Storage Drawers as well would probably speed up the process!

**Comment by NillerMedDild** [comment]
This is still the case I believe, Storage Drawers doesn't really receive updates. I guess I'll close this :< thanks!

**Comment by Boolyman** [comment]
I have given up on this mod because the pipes are so unreliable.  They have completely stopped working in Enigmatica 6... which makes them a pointless addition to the pack.

**Comment by RaVenInTheDark** [comment]
> I have given up on this mod because the pipes are so unreliable. They have completely stopped working in Enigmatica 6... which makes them a pointless addition to the pack.

complaining on a random 1.5year old thread with no info?
