### ISSUE TITLE
[feature] Filter for multiple tags

### ISSUE THREAD

**Issue by TLATER** [Ellpeck/PrettyPipes#98]
Apologies if I'm missing something obvious that's already possible, but I'd like to use the tag filter to filter multiple types of block into certain chests (i.e., in this case types of sand and types of gravel).

When clicking a tag option, previously selected tags are disabled currently:

![2021-11-23T00:36:07](https://user-images.githubusercontent.com/6654841/142955274-f8a38d44-8c7a-4014-8318-6f0da4e3a8b8.png)

**Comment by Ellpeck** [comment]
This is the intended behavior. You can attach multiple pipes to a chest if you want to filter by multiple tags.

**Comment by TLATER** [comment]
Ah, well, regardless of intentional, I wrote this as a feature request to see if the current behavior could be changed to support a new use case :)

My use case is auto-sorting stuff into a nice array of barrels, as should be somewhat visible in the screenshot. This isn't possible with multiple pipes, and even with multiple pipes you're limited to 6 tags (or at most 5 if the container should remain usable), which makes more complex sorting impossible.

I realize this is a Minecraft mod issue list, so I want to explicitly say that I don't expect this to be implemented, I'm just floating the idea and implicitly asking about the reason behind the current design.

**Comment by Ellpeck** [comment]
The tag filter is intended to filter things like "all ores" and "all ingots", it's not intended to be used for.. "all types of sand", which I personally find a little weird to begin with. How many types of sand could your modpack possibly contain? If it's more than, say, 10, then it's too many types of sand. And if it's 10 or less, you're much better off just putting them all into a filter. If you use the largest filter module and two additional filter increase modifiers, there are more than enough slots for that.

I was hesitant to implement a tag filter in the first place, because tags are not something that should be exposed to the player in such an obvious and direct way (similarly to how I believe that chunks and especially the term "chunk loaders" should not have to be exposed directly to players). All of these things are backend mechanics that have little to nothing to do with the actual gameplay. The tag filter is deliberately limited to inspire players to come up with better solutions than making use of what is essentially an engine feature.
